include:
  - docker-compose.networks.yml
services:
  internet-enabled-sd-webui:
    ports:
    - "${WEBUI_PORT}:${WEBUI_PORT}"
    extends:
      file: docker-compose.base.yml
      service: sd-webui
    networks:
      - sd-webui-external-network
